// <auto-generated />
using System;
using EventCatalog.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace EventCatalog.data.Migrations
{
    [DbContext(typeof(EventCatalogDbContext))]
    [Migration("20261009121242_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("EventCatalog.Features.Events.Models.Event", b =>
                {
                    b.Property<Guid>("EventId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTime>("OnSaleFrom")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("VenueId")
                        .HasColumnType("uuid");

                    b.HasKey("EventId");

                    b.HasIndex("VenueId");

                    b.ToTable("Events");
                });

            modelBuilder.Entity("EventCatalog.Features.Events.Models.EventSectionPrice", b =>
                {
                    b.Property<Guid>("EventId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("SectionId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("Price")
                        .HasColumnType("numeric");

                    b.HasKey("EventId", "SectionId");

                    b.HasIndex("SectionId");

                    b.ToTable("EventSectionPrice");
                });

            modelBuilder.Entity("EventCatalog.Features.Venues.Models.Seat", b =>
                {
                    b.Property<Guid>("SeatId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("Number")
                        .HasColumnType("integer");

                    b.Property<string>("Row")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<Guid>("SectionId")
                        .HasColumnType("uuid");

                    b.HasKey("SeatId");

                    b.HasIndex("SectionId", "Row", "Number")
                        .IsUnique();

                    b.ToTable("Seats");
                });

            modelBuilder.Entity("EventCatalog.Features.Venues.Models.Section", b =>
                {
                    b.Property<Guid>("SectionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<Guid>("VenueId")
                        .HasColumnType("uuid");

                    b.HasKey("SectionId");

                    b.HasIndex("VenueId");

                    b.ToTable("Sections");
                });

            modelBuilder.Entity("EventCatalog.Features.Venues.Models.Venue", b =>
                {
                    b.Property<Guid>("VenueId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("SeatingType")
                        .HasColumnType("integer");

                    b.Property<string>("VenueAddress")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<int>("VenueCapacity")
                        .HasColumnType("integer");

                    b.Property<string>("VenueName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("VenueId");

                    b.ToTable("Venues");
                });

            modelBuilder.Entity("EventCatalog.Features.Venues.Models.VenueSeatingMap", b =>
                {
                    b.Property<Guid>("VenueSeatingMapId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("StorageKey")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("VenueId")
                        .HasColumnType("uuid");

                    b.HasKey("VenueSeatingMapId");

                    b.HasIndex("VenueId");

                    b.ToTable("VenueSeatingMaps");
                });

            modelBuilder.Entity("EventCatalog.Features.Events.Models.Event", b =>
                {
                    b.HasOne("EventCatalog.Features.Venues.Models.Venue", "Venue")
                        .WithMany("Events")
                        .HasForeignKey("VenueId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Venue");
                });

            modelBuilder.Entity("EventCatalog.Features.Events.Models.EventSectionPrice", b =>
                {
                    b.HasOne("EventCatalog.Features.Events.Models.Event", "Event")
                        .WithMany("SectionPrices")
                        .HasForeignKey("EventId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EventCatalog.Features.Venues.Models.Section", "Section")
                        .WithMany("EventPrices")
                        .HasForeignKey("SectionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Event");

                    b.Navigation("Section");
                });

            modelBuilder.Entity("EventCatalog.Features.Venues.Models.Seat", b =>
                {
                    b.HasOne("EventCatalog.Features.Venues.Models.Section", null)
                        .WithMany("Seats")
                        .HasForeignKey("SectionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("EventCatalog.Features.Venues.Models.Section", b =>
                {
                    b.HasOne("EventCatalog.Features.Venues.Models.Venue", null)
                        .WithMany("VenueSections")
                        .HasForeignKey("VenueId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("EventCatalog.Features.Venues.Models.VenueSeatingMap", b =>
                {
                    b.HasOne("EventCatalog.Features.Venues.Models.Venue", null)
                        .WithMany("SeatingMaps")
                        .HasForeignKey("VenueId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("EventCatalog.Features.Events.Models.Event", b =>
                {
                    b.Navigation("SectionPrices");
                });

            modelBuilder.Entity("EventCatalog.Features.Venues.Models.Section", b =>
                {
                    b.Navigation("EventPrices");

                    b.Navigation("Seats");
                });

            modelBuilder.Entity("EventCatalog.Features.Venues.Models.Venue", b =>
                {
                    b.Navigation("Events");

                    b.Navigation("SeatingMaps");

                    b.Navigation("VenueSections");
                });
#pragma warning restore 612, 618
        }
    }
}
